# Generated by Django 6.1 on 2026-08-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemapp',
            name='icon',
            field=models.URLField(max_length=500),
        ),
    ]
