# Generated by Django 6.1 on 2026-08-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_systemapp_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemapp',
            name='icon',
            field=models.ImageField(upload_to='icons/'),
        ),
    ]
