# Generated by Django 6.1 on 2026-08-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_systemapp_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemapp',
            name='backend_repo',
            field=models.URLField(blank=True, help_text='GitHub Backend Link', null=True),
        ),
        migrations.AddField(
            model_name='systemapp',
            name='description',
            field=models.TextField(blank=True, help_text='Project overview', null=True),
        ),
        migrations.AddField(
            model_name='systemapp',
            name='frontend_repo',
            field=models.URLField(blank=True, help_text='GitHub Frontend Link', null=True),
        ),
        migrations.AddField(
            model_name='systemapp',
            name='live_link',
            field=models.URLField(blank=True, help_text='Live Hosted URL', null=True),
        ),
        migrations.AddField(
            model_name='systemapp',
            name='tech_stack',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
