# Generated by Django 6.1 on 2026-08-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_systemapp_backend_repo_systemapp_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='system_icons/')),
                ('project_name', models.CharField(default='My Portfolio OS', max_length=200)),
                ('frontend_engine', models.CharField(blank=True, max_length=200, null=True)),
                ('backend_architecture', models.CharField(blank=True, max_length=200, null=True)),
                ('database_system', models.CharField(blank=True, max_length=200, null=True)),
                ('active_libraries', models.TextField(blank=True, null=True)),
                ('hosting_environment', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'System OS Info',
            },
        ),
    ]
