# Generated by Django 6.1 on 2026-08-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_systemos'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemapp',
            name='project_type',
            field=models.CharField(choices=[('Personal Project', 'Personal Project'), ('Client Project', 'Client Project'), ('Startup', 'Startup')], default='Personal Project', help_text='Categorize this application', max_length=50),
        ),
    ]
